"""Synthetic v6 source fixtures using the public preservation/review protocol.

These helpers simulate a reviewer for PDFs generated by the tests themselves. They
are not evidence about production PDF coverage and never patch a production gate.
"""
from __future__ import annotations

from pathlib import Path

import fitz

from littrans.fidelity import build_source_review_packet, import_source_review, prepare_source
from littrans.models import SourceUnit
from littrans.storage import load_project, read_json, sha256_file, write_json


def prepare_plain_text_fixture(root: Path, expected_units: list[SourceUnit]) -> None:
    """Preserve generated prose, then import source-bound IDs and review receipts."""
    config = load_project(root)
    with fitz.open(config.source(root)) as document:
        for unit in expected_units:
            assert document[unit.page - 1].get_text().split() == unit.source_text.split()
    prepare_source(root, allow_missing_layout=True)
    packet = build_source_review_packet(root)
    review = read_json(Path(packet["review_template"]))
    review["reviewer"] = "synthetic-source-fixture-oracle"
    by_page = {unit.page: unit for unit in expected_units}
    for decision in review["pages"]:
        unit = by_page[decision["page"]]
        decision["override"] = {
            "regions": [],
            "units": [{
                "unit_id": unit.unit_id,
                "source_markdown": unit.source_text,
                "bbox": list(unit.bbox),
                "kind": unit.kind.value,
            }],
        }
    review_path = root / "tmp" / "fixture-source-review.json"
    write_json(review_path, review)
    result = import_source_review(root, review_path, confirm_visual_review=True)
    assert result["requires_new_packet"]
    packet = build_source_review_packet(root)
    review = read_json(Path(packet["review_template"]))
    evidence = read_json(Path(packet["packet_path"]))
    review["reviewer"] = "synthetic-source-fixture-oracle"
    for page in evidence["pages"]:
        image = root / page["ledger"]["page_image"]
        pixmap = fitz.Pixmap(str(image))
        assert pixmap.width > 0 and pixmap.height > 0
        assert sha256_file(image) == page["ledger"]["page_image_sha256"]
        assert not page["assets"]  # Generated fixture is explicitly prose-only.
        assert [unit["unit_id"] for unit in page["units"]] == [by_page[page["page"]].unit_id]
    for decision in review["pages"]:
        for field in ("viewed_original", "coverage_complete", "boundaries_complete",
                      "reading_order_correct", "grouping_checked", "layout_fallback_checked"):
            decision[field] = True
        decision["notes"] = "Test-only oracle for generated prose; source text, page raster and unit IDs checked."
    write_json(review_path, review)
    result = import_source_review(root, review_path, confirm_visual_review=True)
    assert result["approved_pages"] == sorted(by_page)


def original_image_evidence(root: Path, unit: SourceUnit) -> dict[str, str]:
    """Return real image fingerprints for synthetic translation records."""
    result = {}
    paths = [asset.path for asset in unit.asset_refs]
    page_path = f"evidence/pages/fidelity-p{unit.page:04d}.png"
    if (root / page_path).is_file():
        paths.append(page_path)
    for relative in paths:
        image = root / relative
        pixmap = fitz.Pixmap(str(image))
        assert pixmap.width > 0 and pixmap.height > 0
        result[relative] = sha256_file(image)
    return result


def review_fixture_metadata(root: Path) -> None:
    """Bind a fresh synthetic review after metadata-only fixture edits.

    This is deliberately limited to fixtures with no image assets. Real asset
    geometry/content needs source correction packets and independent visual review.
    """
    packet = build_source_review_packet(root)
    evidence = read_json(Path(packet["packet_path"]))
    assert all(not page["assets"] for page in evidence["pages"]), (
        "Metadata fixture review must never approve real or changed asset images"
    )
    review = read_json(Path(packet["review_template"]))
    review["reviewer"] = "synthetic-metadata-fixture-oracle"
    for decision in review["pages"]:
        for field in ("viewed_original", "coverage_complete", "boundaries_complete",
                      "reading_order_correct", "grouping_checked", "layout_fallback_checked"):
            decision[field] = True
        decision["notes"] = (
            "Synthetic metadata regression fixture, no original complex assets. "
            "The test supplies the classification/ownership oracle; this is not a production coverage claim."
        )
    path = root / "tmp" / "fixture-metadata-review.json"
    write_json(path, review)
    result = import_source_review(root, path, confirm_visual_review=True)
    assert result["approved_pages"] == packet["pages"]


def make_asset_fixture(tmp_path: Path, entries: list[tuple[str, str, str]]) -> tuple[Path, list[SourceUnit], object]:
    """Generate known prose+label pages and preserve actual complex-region originals."""
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas

    from littrans.batching import create_batches
    from littrans.project import initialize_project
    from littrans.storage import read_jsonl

    pdf = tmp_path / "asset-fixture.pdf"
    drawing = canvas.Canvas(str(pdf), pagesize=letter)
    for prose, _kind, label in entries:
        drawing.drawString(54, 740, prose)
        drawing.drawString(60, 650, label)
        drawing.showPage()
    drawing.save()
    root = tmp_path / "asset-project"
    initialize_project(pdf, root, "technical-book", "Original asset fixture")
    prepare_source(root, allow_missing_layout=True)
    packet = build_source_review_packet(root)
    review = read_json(Path(packet["review_template"]))
    review["reviewer"] = "synthetic-region-fixture-oracle"
    with fitz.open(pdf) as document:
        for decision in review["pages"]:
            page = decision["page"]
            prose, kind, label = entries[page - 1]
            bbox = [54, 122, 500, 160]
            assert label == document[page - 1].get_text(clip=fitz.Rect(bbox)).strip()
            aid = f"fixture-asset-{page}"
            decision["override"] = {
                "regions": [{"id": aid, "kind": kind, "bbox": bbox, "display": False}],
                "units": [{"unit_id": f"u{page:03d}", "kind": "paragraph", "bbox": [45, 35, 560, 170],
                           "source_markdown": prose + " {{asset:" + aid + "}}"}],
            }
    path = root / "tmp" / "asset-fixture-regions.json"
    write_json(path, review)
    import_source_review(root, path, confirm_visual_review=True)
    packet = build_source_review_packet(root)
    review = read_json(Path(packet["review_template"]))
    evidence = read_json(Path(packet["packet_path"]))
    review["reviewer"] = "synthetic-region-fixture-oracle"
    for page in evidence["pages"]:
        asset = page["assets"][0]
        fragment = asset["fragments"][0]
        pixmap = fitz.Pixmap(str(root / fragment["png_path"]))
        assert pixmap.width > 0 and pixmap.height > 0
        assert asset["id"] == f"fixture-asset-{page['page']}"
        assert fragment["glyph_ids"]  # The retained labels are original PDF glyphs.
    for decision in review["pages"]:
        for field in ("viewed_original", "coverage_complete", "boundaries_complete",
                      "reading_order_correct", "grouping_checked", "layout_fallback_checked"):
            decision[field] = True
        decision["notes"] = "Generated fixture oracle: exact PDF labels, region extents and original raster checked."
    write_json(path, review)
    import_source_review(root, path, confirm_visual_review=True)
    units = read_jsonl(root / "derived" / "units.jsonl", SourceUnit)
    manifests = create_batches(root, "all", max_words=900, prefix="assets")
    assert len(manifests) == 1
    return root, units, manifests[0]


def correct_plain_fixture_units(root: Path, page_units: dict[int, list[dict[str, object]]]) -> list[SourceUnit]:
    """Apply bound reading-order/paragraph corrections that preserve generated PDF text."""
    from littrans.storage import read_jsonl

    config = load_project(root)
    with fitz.open(config.source(root)) as document:
        for page, units in page_units.items():
            actual = document[page - 1].get_text().split()
            proposed = " ".join(str(unit["source_markdown"]) for unit in units).split()
            assert proposed == actual, "A fixture correction must preserve original PDF prose"
    packet = build_source_review_packet(root, ",".join(str(page) for page in page_units))
    review = read_json(Path(packet["review_template"]))
    review["reviewer"] = "synthetic-paragraph-fixture-oracle"
    for decision in review["pages"]:
        decision["override"] = {"regions": [], "units": page_units[decision["page"]]}
    path = root / "tmp" / "fixture-paragraph-correction.json"
    write_json(path, review)
    import_source_review(root, path, confirm_visual_review=True)
    review_fixture_metadata(root)
    return read_jsonl(root / "derived" / "units.jsonl", SourceUnit)


def record_fixture_source_issue(root: Path, page: int, message: str) -> None:
    """Record a synthetic new source finding through the current review import."""
    packet = build_source_review_packet(root, str(page))
    review = read_json(Path(packet["review_template"]))
    review["reviewer"] = "synthetic-source-issue-reviewer"
    decision = review["pages"][0]
    for field in ("viewed_original", "boundaries_complete", "reading_order_correct",
                  "grouping_checked", "layout_fallback_checked"):
        decision[field] = True
    decision["coverage_complete"] = False
    decision["issues"] = [message]
    path = root / "tmp" / "fixture-source-issue.json"
    write_json(path, review)
    result = import_source_review(root, path, confirm_visual_review=True)
    assert not result["approved_pages"]
